export enum OrderStatus {
  PENDING = 'PENDING',
  ORDERED = 'ORDERED',
  IN_PROGRESS = 'IN_PROGRESS',
  PACKED = 'PACKED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  CANCELED = 'CANCELED',
}
